### PR TITLE
Update the lineage tutorial

### PR DESCRIPTION
**Pull request by Marius1311**
Emphasize the differences between moslin and a baseline OT approach on the TedSim data.

### CODE REVIEW

**Comment by michalk8** [comment]
@Marius1311 please run the linter, will review later today.

**Comment by Marius1311** [comment]
<p>done, thanks!</p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509396910'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509396918'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok, changed everywhere. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509396919'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509396925'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok, done. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509396933'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok, I included a utility function for this. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509396943'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>I think that was your original check. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509396952'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>done. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509396958'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok, done</p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509396960'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok, done. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509396965'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>perfect, thanks for spotting this!</p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509396972'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>thanks, added that. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509396982'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>Thanks Mike, I added the images in the main repo, adapted the code, and fixed the spelling mistakes. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509396985'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>I also refer to the figure later on using \ref{fig-state_tree}, not sure whether that will really work. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509396985'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>thanks. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509396993'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>I added the class link and rewrote this section. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509397002'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>fixed this, thanks. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509396939'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>good point, thanks. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509396999'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok, done. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509397007'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>done. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509397014'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok!</p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509397018'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>thanks, fixed all of these. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509397024'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>thanks, I fixed all of these. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509397030'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok, done</p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509397033'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>done, thanks. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509397037'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>thanks, fixed both. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509397044'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>POT needs float64, it often does not converge otherwise. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509397049'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>I like them, otherwise I don't know how long I have to wait still. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509397054'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok, done. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509397063'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>I prefer to write numbers until 12. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509397068'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509397071'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>done, good suggestion. </p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509397079'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>good point, thanks!</p>

---

 <a href='https://app.reviewnb.com/theislab/moscot_notebooks/pull/38/discussion/#comment-1509397081'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
This depends on https://github.com/theislab/moscot/pull/525 for references, an updated TedSim data link, and additional references. @michalk8, I think I addressed all of your requested changes. There is a merge conflict because you modified the lineage-problem preparation on main, which should be overwritten by the changes on this branch, though. Would be great if you could have quick final look over this to let me know whether I can merge. Thanks!

**Review by michalk8 — APPROVED** [review]

**Comment by michalk8** [comment]
> This depends on https://github.com/theislab/moscot/pull/525 for references, an updated TedSim data link, and additional references. @michalk8

I updated this to use `moscot.datasets.tedsim` + did some minor formatting changes; LGTM from my side (would double check for typos, but it's late for me).

**Comment by Marius1311** [comment]
Amazing, thanks @michalk8 , I'll check for typos and merge then.

**Pull request merged**
